config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :user_sessions, only: %i[new create] do
    delete :destroy, on: :collection
  end

  root 'hello#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/paginable.rb
module Paginable
  extend ActiveSupport::Concern

  included do
    scope :paginate, (lambda do |per, page|
      return where(nil) if per.blank? || page.blank? || page.zero?
      offset((page.to_i - 1) * per.to_i).limit(per)
    end)
  end
end

app/models/user.rb
class User < ApplicationRecord
  include Paginable

  attr_accessor :password

  validates :email, :password, presence: true
  validates :email, uniqueness: true

  before_create :set_crypted_password

  scope :filter_by_email, ->(email) { where('email like ?', "%#{email}%") }

  def check_password(password)
    crypted_password == Digest::SHA2.hexdigest(password)
  end

  private

  def set_crypted_password
    # TODO: in next version add salt
    assign_attributes(crypted_password: Digest::SHA2.hexdigest(password))
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Authentification
  include Authorization
end

app/controllers/concerns/authentification.rb
module Authentification
  extend ActiveSupport::Concern

  included do
    helper_method :current_user
  end

  private

  def current_user
    if @current_user.nil?
      @current_user = User.find_by(id: session[:user_id]) || false
    end

    @current_user
  end
end

app/controllers/concerns/authorization.rb
module Authorization
  extend ActiveSupport::Concern

  included do
    helper_method :login_required?, :admin_required?
  end

  private

  def login_required?
    unless current_user
      flash[:danger] = 'Access denied! Please Log In'
      redirect_to new_user_session_path
    end
  end

  def admin_required?
    if !current_user || !current_user.admin?
      flash[:danger] = 'Access denied! Please Log In'
      redirect_to new_user_session_path, danger: 'Access denied'
    end
  end
end

app/controllers/concerns/filterable_users.rb
module FilterableUsers
  extend ActiveSupport::Concern

  private

  def users_filter(users, params)
    filter_by_email(users, params)
  end

  def filter_by_email(users, params)
    if params[:query] && params[:query][:email].present?
      return users.filter_by_email(params[:query][:email])
    end

    users
  end
end

app/controllers/concerns/pagination.rb
module Pagination
  extend ActiveSupport::Concern

  included do
    helper_method :per_page, :pagination_block, :current_page

    private

    def per_page
      params[:per] || self.class.class_variable_get(:@@_pagination_per)
    end

    def pagination_block(model)
      return [] if current_page.zero?
      total_pages = calculate_total_pages(model.unscope(:offset, :limit).count)
      pages = []
      3.downto(1).each { |index| pages << current_page - index }
      pages << current_page
      1.upto(3).each { |index| pages << current_page + index }
      pages.delete_if { |page| page < 1 || page > total_pages }
      pages
    end

    def calculate_total_pages(count)
      count / per_page + ((count % per_page.to_f).zero? ? 0 : 1)
    end

    def current_page
      if @current_page.nil?
        @current_page = params[:page].blank? ? 1 : params[:page].to_i
      end

      @current_page
    end
  end

  class_methods do
    def per_page_default(per)
      class_variable_set(:@@_pagination_per, per)
    end
  end
end

app/controllers/hello_controller.rb
class HelloController < ApplicationController
  before_action :login_required?
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  layout 'authentification'

  def new
  end

  def create
    user = User.where(email: params[:email]).first
    if user
      if user.check_password(params[:password])
        session[:user_id] = user.id
        redirect_to root_path
      else
        render :new, notice: 'Password incorrect'
      end
    else
      render :new, notice: 'User not found'
    end
  end

  def destroy
    session.clear

    redirect_to new_user_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include FilterableUsers
  include Pagination
  per_page_default 5

  before_action :admin_required?, except: %i[new create]
  before_action :set_user, only: %i[show edit update destroy]

  def index
    @users = users_filter(User.all, params)
    @users = @users.paginate(per_page, current_page)
  end

  def new
    @user = User.new

    render layout: 'authentification'
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to new_user_session_path, notice: 'User was successfully created. Please sign in now.'
    else
      render :new, layout: 'authentification'
    end
  end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @user.destroy

    redirect_to users_url, notice: 'User was successfully destroyed.'
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(%i[email password admin])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def boolean_to_string(bool)
    bool ? 'Yes' : 'No'
  end
end

app/helpers/hello_helper.rb
module HelloHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/hello/index.html.erb
<h1>Hello world!</h1>

<% if current_user %>
  Your Email <%= current_user.email %>
<% end %>

app/views/layouts/_footer.html.erb
<div class="d-flex w-100 h-100 p-3 mx-auto flex-column">
  <footer class="mastfoot mt-auto">
    <div class="inner">
      <p class="mt-5 mb-3 text-muted">&copy; 2017-2018</p>
    </div>
  </footer>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SimpleAuthentification</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag 'favicon.ico' %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="text-center">
    <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
      <header class="masthead mb-auto">
        <div class="inner">
          <h3 class="masthead-brand">SimpleAuth</h3>
          <nav class="nav nav-masthead justify-content-center">
            <%= link_to 'Home', root_path, class: 'nav-link' %>

            <% if current_user && current_user.admin? %>
              <%= link_to 'Users', users_path, class: 'nav-link' %>
            <% end %>

            <% if !current_user %>
              <%= link_to 'Sign Up', new_user_path, class: 'nav-link' %>
              <%= link_to 'Sign In', new_user_session_path, class: 'nav-link' %>
            <% end %>

            <% if current_user %>
              <%= link_to 'Log out', user_sessions_path, method: :delete, class: 'nav-link' %>
            <% end %>
          </nav>
        </div>
      </header>

      <main role="main" class="inner cover">
        <%= yield %>
      </main>

      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/layouts/authentification.html.erb
<html>
  <head>
    <title>SimpleAuthentification</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag 'favicon.ico' %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="text-center">
    <div class="container">
      <% unless flash.empty? %>
        <div class="row">
          <div class="col align-self-center">
            <% flash.each do |key, message| %>
              <div class="alert alert-<%= key %>" role="alert">
                <%= message %>
              </div>
            <% end %>
          </div>
        </div>
      <% end %>

      <div class="row">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/user_sessions/new.html.erb
<%= form_tag user_sessions_path, method: :post, class: 'form-signin' do %>
  <h1 class="h3 mb-3 font-weight-normal">Please sign in</h1>

  <%= label_tag :email, 'Email address', class: 'sr-only' %>
  <%= text_field_tag :email, nil,
                     class: 'form-control',
                     placeholder: 'Email address',
                     type: :email,
                     required: true,
                     autofocus: true %>

  <%= label_tag :password, 'Password', class: 'sr-only' %>
  <%= text_field_tag :password, nil,
                     class: 'form-control',
                     placeholder: 'Password',
                     type: :password,
                     required: true %>

  <%= submit_tag 'Sign in', class: 'btn btn-lg btn-primary btn-block' %>

  or <%= link_to 'sign up', new_user_path %>
<% end %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true, class: 'form-signin') do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.label :email, 'Email address' %>
    <%= form.text_field :email,
                      class: 'form-control',
                      type: :email,
                      required: true,
                      autofocus: true %>

    <div class="custom-control custom-checkbox">
      <%= form.check_box :admin, class: 'custom-control-input' %>
      <%= form.label :admin, 'Is admin', class: 'custom-control-label' %>
    </div>

    <%= form.submit 'Save', class: 'btn btn-lg btn-primary btn-block' %>
  </div>
<% end %>

app/views/users/_pagination.html.erb
<% if pages.present? %>
  <nav aria-label="Pagination">
    <ul class="pagination">
      <% pages.each do |page| %>
        <li class="page-item<%= (page == current_page) ? ' active' : '' %>">
          <%= link_to page, users_path(request.query_parameters.merge(page: page)), class: 'page-link' %>
        </li>
      <% end %>
    </ul>
  </nav>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<div class="search-block">
  <%= form_tag users_path, method: :get do %>
    <%= label_tag 'query[email]', 'Email: ' %>
    <%= search_field_tag 'query[email]', params[:query].try(:[], :email) %>

    <%= submit_tag "Find" %>
  <% end %>
</div>

<hr />

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Admin</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= boolean_to_string(user.admin?) %></td>
        <td><%= link_to 'Show', user, class: 'btn btn-light' %></td>
        <td><%= link_to 'Edit', edit_user_path(user), class: 'btn btn-light' %></td>
        <td>
          <%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-light' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="pagination">
  <%= render 'pagination', pages: pagination_block(@users), current_page: current_page %>
</div>

<br>

<%= link_to 'New User', new_user_path, class: 'btn btn-primary' %>

app/views/users/new.html.erb
<%= form_for @user, method: :post, html: { class: 'form-signin' } do |form| %>
  <h1 class="h3 mb-3 font-weight-normal">Please sign up</h1>

  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this @user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.label :email, 'Email address' %>
  <%= form.text_field :email,
                     class: 'form-control',
                     type: :email,
                     required: true,
                     autofocus: true %>

  <%= form.label :password, 'Password' %>
  <%= form.text_field :password,
                     class: 'form-control',
                     type: :password,
                     required: true %>

  <div class="custom-control custom-checkbox">
    <%= form.check_box :admin, class: 'custom-control-input' %>
    <%= form.label :admin, 'Is admin', class: 'custom-control-label' %>
  </div>

  <%= form.submit 'Sign up', class: 'btn btn-lg btn-primary btn-block' %>

  or <%= link_to 'sign in', new_user_session_path %>
<% end %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  Email: <%= @user.email %>
</p>

<p>
  Admin: <%= boolean_to_string(@user.admin?) %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>